[package]
name = "hackerscript-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
anyhow = "1.0"
thiserror = "1.0"

[[bin]]
name = "HackerScript-Compiler"
path = "src/main.rs"

