[package]
name = "hsdf"
version = "0.3.0"
edition = "2021"

[dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
clap = { version = "4.5.54", features = ["derive"] }
regex = "1.12.2"
thiserror = "2.0.17"
